-- UNION (EXCLUI VALORES DUPLICADOS)

SELECT EMPLOYEE_ID, JOB_ID FROM HR.EMPLOYEES 
UNION 
SELECT EMPLOYEE_ID, JOB_ID FROM HR.JOB_HISTORY ORDER BY EMPLOYEE_ID;

SELECT EMPLOYEE_ID, JOB_ID, TO_DATE(NULL) AS "INICIO", TO_DATE(NULL) AS "FINAL" FROM HR.EMPLOYEES 
UNION 
SELECT EMPLOYEE_ID, JOB_ID, START_DATE, END_DATE FROM HR.JOB_HISTORY ORDER BY EMPLOYEE_ID;

-- UNION ALL (NÃO EXCLUI VALORES DUPLICADOS)

SELECT EMPLOYEE_ID, JOB_ID FROM HR.EMPLOYEES
UNION ALL
SELECT EMPLOYEE_ID, JOB_ID FROM HR.JOB_HISTORY ORDER BY EMPLOYEE_ID;

-- INTERSECT (RETORNA DADOS COMUNS NOS DOIS SELECTs)

SELECT EMPLOYEE_ID, JOB_ID FROM HR.EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID, JOB_ID FROM HR.JOB_HISTORY ORDER BY EMPLOYEE_ID;

-- MINUS (RETORNA DADOS CONSULTADO NO 1SELECT QUE NÃO CONSTEM NO 2SELECT)

SELECT EMPLOYEE_ID, JOB_ID FROM HR.EMPLOYEES
MINUS
SELECT EMPLOYEE_ID, JOB_ID FROM HR.JOB_HISTORY ORDER BY EMPLOYEE_ID;

--VIEW (É um tipo especial de visualização dos dados de uma ou várias tabelas.)

CREATE VIEW CLIENTE_ID5 AS
SELECT ID, NOME, ENDERECO, TELEFONE FROM CLIENTES WHERE ID = 5; -- CRIAÇÃO DA VIEW 

SELECT * FROM CLIENTE_ID5; -- EXECUTANDO A VIEW 

DESCRIBE CLIENTE_ID5; -- ESTRUTURA DA VIEW 

DROP VIEW CLIENTW_ID5; -- APAGAR A VIEW 